name: Orange Lambda Stack
canonical: orange_lambda_stack
author: Kamal Pant
description: stack for lambda and orange.
type: stack
image: ""
keywords:
- orange, lambda, aws, terraform
technologies: []
config:
  pipeline:
    pipeline:
      path: pipeline/terraform-pipeline.yaml
    variables:
      path: pipeline/variables.sample.yaml
