# Configuration of the CI pipeline

name: 'Terraform FE implementation'
canonical: 'Terraform with FE'
description: 'Stack which will help us to implement an FE instance using Terraform'
keywords:
  - 'FE'
  - 'Terraform'
  - 'Concourse'
technologies:
  - technology: FE
  - version: n/a
author: 'Cycloid'
image: 'https://raw.githubusercontent.com/cycloid-community-catalog/docs-step-by-step-stack/stacks/icon.png'
type: 'stack'
config:
  # configuration of the CI pipeline
  pipeline:
    pipeline:
      path: 'pipeline/pipeline.yml'

    variables:
      path: 'pipeline/variables.sample.yml'
